### ISSUE TITLE
kldload: Cannot load any module

### ISSUE THREAD

**Issue by astro** [nixos-bsd/nixbsd#15]
I get this error when trying to load any module:

```
kldload: unexpected relocation type 42, symbol index 456
link_elf_obj: symbol __stack_chk_guard undefined
linker_load_file: /nix/store/r13san988d8yjicihlbp452rBy3vzjn3-sys-x86_64-unknown-freebsd-14.8/kernel/pf.ko - unsupported file type
kldload: an error occurred while loading module pf. Please check dmesg(8) for more details.
```

**Comment by artemist** [comment]
We disable the hardening flags that we think would cause this in our [sys package](https://github.com/rhelmot/nixpkgs/blob/freebsd-staging/pkgs/os-specific/bsd/freebsd/sys.nix#L38) but it doesn't seem to work for all modules.

 Some modules, like nullfs, do still load properly, but most I've tested don't.

**Comment by artemist** [comment]
Should be fixed in https://github.com/rhelmot/nixpkgs/commit/ed74f89b99f84f070c496efba69860de56d27ddb, try `nix flake update` to get it. It might be a good idea to investigate why disabling the `stackprotector` hardening flag didn't work though.
