### ISSUE TITLE
Social media request

### ISSUE THREAD

**Issue by etrigan63** [nixos-bsd/nixbsd#20]
Any chance you folks will have a presence on Mastodon? Fosstodon.org hosts a large Nix/NixOS community.

**Comment by rhelmot** [comment]
This project isn't really at the stage where we feel comfortable having a public face other than this github org. If you want notifications about progress, feel free to subscribe to this repository. If you want to contribute, feel free, but if you want support it needs to be in the context of being a contributor or just doing normal bug reports.
