### ISSUE TITLE
Figure out kldxref on cross builds

### ISSUE THREAD

**Issue by artemist** [nixos-bsd/nixbsd#28]
FreeBSD will not load module dependencies unless it has a `linker.hints` file in the modules directory. We can do this during build on native builds, but there seems to be no way to compile the required `kldxref` tool with compat for cross-builds.

We should figure out how to make a service that runs `kldxref` on first boot, or decide to not care about cross builds.

**Comment by rhelmot** [comment]
first boot services are easy with rc - the system keeps a "first boot sentinel" and will automatically only run services tagged `firstboot` when it is missing, then automatically creates the sentinel.

**Comment by artemist** [comment]
True, the problem is that we would want to put `linker.hints` with the kernel modules, which is in the store

**Comment by rhelmot** [comment]
on one hand! we already have services which cannot build cross, it's "the entire graphical system"

on the other hand! we should really care about cross!

**Comment by rhelmot** [comment]
maybe just do #12 and suffer

**Comment by artemist** [comment]
My current solution is to only run kldxref on native builds, and you don't get dependencies on cross builds, not optimal but it's easy.

**Comment by rhelmot** [comment]
we did in fact eventually get kldxref to run cross
