### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by artemist** [nixos-bsd/nixbsd#3]
If we want to be able to upstream any code from this repository once there are additional contributors we should add a license. A fair amount of the code is copied from NixOS, so we're already required to give notice that those are under the MIT license from NixOS contributors.

I would be fine with releasing under MIT, but that obviously requires both @rhelmot and @artemist to consent.

**Comment by rhelmot** [comment]
This project is totally appropriate for MIT in my opinion. I consent to that.
