### ISSUE TITLE
Do you use `nix/misc/systemv/nix-daemon`?

### ISSUE THREAD

**Issue by roberth** [nixos-bsd/nixbsd#32]
It seems that we have this untested [misc/systemv/nix-daemon](https://github.com/NixOS/nix/blob/master/misc/systemv/nix-daemon) file in the Nix package manager, and I was wondering whether you are using it.
It would be great if we could reuse your testing infrastructure to make sure that any changes to it are correct.

Context:
- https://github.com/NixOS/nix/pull/11103

**Comment by rhelmot** [comment]
Nope, FreeBSD isn't a sysv init system so we're using a fork with a specific freebsd-rc daemon configuration added. See here: https://github.com/rhelmot/nix/tree/freebsd-staging/misc/freebsd-rc

**Comment by roberth** [comment]
Ah ok, that answers the question then.
I think we could accept that file upstream if you can provide an expression that tests it, but I'll close this for now.
Thank you!
